### ISSUE TITLE
Collapsed SearchView clears filter and causes issues with Map and Details

### ISSUE THREAD

**Issue by robert-w-gries** [end-hunger-durham/pantries-android#18]
We should also use this opportunity to improve our story on handling `SearchView` during fragment/page changes.

**Comment by robert-w-gries** [comment]
Bug is more severe than thought and needs to be fixed in beta.  Opening `SearchView` and clicking on `InfoWindow` in `MapFragment` causes `null` details to be filled

**Comment by hkoslow** [comment]
To reproduce problem:
- Open app to Maps view and search on 27703
- Zoom on resulting map and click on northern-most pin (Antioch Baptist Church)
- Click on the pop-up info box for Antioch 
- Pantry entry is displayed with map of the world (!) and fields filled with "null null" or "null"

Other, seemingly random, pantries selected from the map view behave the same way, but this one is easy to reproduce consistently.
