### ISSUE TITLE
Displays pantry entry with "null null" in all fields

### ISSUE THREAD

**Issue by hkoslow** [end-hunger-durham/pantries-android#22]
Not sure which pantry was selected from the map view, but it displayed with "null null" in all fields. See attached screen shot.
![display null pantry entry](https://user-images.githubusercontent.com/14024361/52907502-cebfb500-3230-11e9-824e-6614ff55b0f4.jpg)

**Comment by robert-w-gries** [comment]
We're tracking this issue in #18
